markdown: kramdown
pygments: true
permalink: /:year/:month/:day/:title 
auto: true
rdiscount:
  extensions: [smart]
title : Daniel Wheeler
production_url : http://wd15.github.io
description: "Daniel Wheeler's Research Blog"
disqus_shortname: wd15
analytics: 
gauges: 
author :
  name : Daniel Wheeler
  github : wd15
  twitter : 
  email: daniel.wheeler2@gmail.com

imageurl: http://www.ctcms.nist.gov/~wd15/jekyll_images
